In [ ]:
#Esercizio1
#L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: 
#lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] 
#trasformiamola in un array NumPy (casting): lst = np.array(lst) e rispondiamo alle domande del CEO della Object SpA: 
#qual è stata la vendita massima mensile? E quella minima?
#quali sono le vendite mensili maggiori di 5000 oggetti?
#E quante ne sono?
#quali sono le vendite minori di 3000 oggetti?

In [5]:
import numpy as np

In [9]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]

In [11]:
#trasformo la lista in un array 
lst = np.array(lst)

In [13]:
#calcolo la vendita massima 
vendita_massima = np.max(lst)
vendita_massima

8150

In [15]:
#calcolo la vendita minima
vendita_minima = np.min(lst)
vendita_minima

1280

In [17]:
#calcolo le vendite maggiori di 5000
vendite_maggiori_5000 = lst[lst > 5000]
vendite_maggiori_5000

array([5500, 7200, 6410, 8150, 7100, 5350])

In [23]:
#conto quante sono le vendite maggiori di 5000
vendite_maggiori_5000.size

6

In [25]:
#calcolo le vendite minori di 3000
vendite_minori_3000 = lst[lst < 3000]
vendite_minori_3000

array([2000, 1280, 1900, 2500])

In [27]:
#conto quante sono le vendite minori di 3000
vendite_minori_3000.size

4

In [29]:
#calcolo la media di quanti oggetti sono stati venduti al mese
media_oggetti_venduti = np.mean(lst)
media_oggetti_venduti

4634.166666666667

In [31]:
#Esercizio 3
#L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray: 
#import numpy as np 
#stipendi = np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] ) 
#L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi:
#con un ciclo for
#con il masking



In [33]:
import numpy as np
stipendi = np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] ) 

In [43]:
#CICLO FOR
stipendi_raddoppiati_for = []
for stipendio in stipendi:
    stipendio_raddoppiato = stipendio * 2
    stipendi_raddoppiati_for.append(stipendio_raddoppiato)
    
print(stipendi_raddoppiati_for)


[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]


In [49]:
#MASKING
stipendi_raddoppiati_masking = stipendi * 2
print(stipendi_raddoppiati_masking)

[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


In [ ]:
#Esercizio4
#Scrivere un programma che, data una lista di numeri, fornisca in output i tre numeri più grandi; gestire il caso in cui la lista sia più corta di tre, 
#e quando uno o più dei numeri selezionati sono uguali.

In [142]:
numeri = [10, 20, 50, 70, 90, 100]
lunghezza_lista = len(numeri)
if lunghezza_lista <=3:
    print("I massimi sono:", numeri)
else:
    numeeri = set(numeri) #trasformo la lista in un set per eliminare i duplicati. I set non ammettono valori duplicati
    numeri = list(numeri) #trasformo poi nuovamente il set in una lista dato che il set non è ordinato, mentre la lista sì
    numeri.sort(reverse=True)
    print("I massimi sono:", numeri[:3])

I massimi sono: [100, 90, 70]


In [ ]:
#Esercizio 5
#Scrivere un programma che:
#in input acquisisce una lista di numeri e un numero K
#in output, dovrà restituire la media di tutti i numeri nella lista maggiori o uguali a K
#se non ce ne dovesse essere nessuno, dovrà stampare a schermo un messaggio adeguato.

In [99]:
lista_input = input("Inserisci i numeri separati da virgola")
numeri = [int(x.strip()) for x in lista_input.split(",")]
K = int(input("Inserisci un numero"))

numeri_maggiori_K = []
for numero in numeri:
    if numero >= K:
        numeri_maggiori_K.append(numero)

if numeri_maggiori_K:
    media_numeri_maggiori_K = sum(numeri_maggiori_K) / len(numeri_maggiori_K)
    print("La media dei numeri maggiori o uguali a", K, "è:", media_numeri_maggiori_K)
else:
    print("Nessun numero maggiore o uguale a", K)

Inserisci i numeri separati da virgola 10, 20, 30, 40, 50
Inserisci un numero 15


La media dei numeri maggiori o uguali a 15 è: 35.0


In [144]:
#Soluzione alternativa senza ulizzo ciclo FOR
numeri = [30, 50, 10, 60, 20, 100]
K = 30

numeri = np.array(numeri) #casting
filtro = numeri >= K
selezione = numeri[filtro]
if len(selezione) > 0:
    media_numeri_selezione = selezione.mean()
    print("La media dei numeri maggiori di", K, "è:", media_numeri_selezione)
else:
    print("Non ci sono numeri maggiori o uguali a", K)


La media dei numeri maggiori di 30 è: 60.0


In [150]:
#Esercizio 6
#Scrivere un programma che, data una lista di numeri, come output stamperà lo stesso numero di asterischi su righe diverse, ottenendo una semplice visualizzazione grafica
lista_input = input("Inserisci i numeri separati da virgola")
numeri = [int(x.strip()) for x in lista_input.split(",")]

for numero in numeri:
    print("*" * numero, numero)


Inserisci i numeri separati da virgola 5, 4, 3, 2


***** 5
**** 4
*** 3
** 2


In [109]:
#Esercizio 7
#Abbiamo una lista di codici fiscali: 
#lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"]
#trovare i codici fiscali che contengono "95", metterli in una lista, e alla fine stamparla;
#inoltre, per ognuno di essi, stampare a video i caratteri relativi al nome e quelli relativi al cognome

lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"]

codici_con_95 = []
for codice in lista_cf:
    if "95" in codice:
        codici_con_95.append(codice)
print(codici_con_95)

for codice_con_95 in codici_con_95:
    cognome = codice_con_95[0:3]
    nome = codice_con_95[3:6]
    print("Codice:", codice_con_95, "Cognome:", cognome, "Nome", nome)
    


['ABCDEF95G01A123B', 'STUVWX95Z04A654E', 'DEFGHI95J06A987G']
Codice: ABCDEF95G01A123B Cognome: ABC Nome DEF
Codice: STUVWX95Z04A654E Cognome: STU Nome VWX
Codice: DEFGHI95J06A987G Cognome: DEF Nome GHI


In [ ]:
#Esercizio 8
#Abbiamo tre liste della stessa lunghezza, dove ogni elemento nella medesima posizione si riferisce ai dati dello stesso studente:
#studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"]
#corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"]
#edizioni = [1, 2, 3, 2, 2, 1, 3, 3]
#Stampare a video tutti e soli gli studenti che frequentano una prima edizione; non tutti i dati potrebbero essere necessari.

In [168]:
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"]
corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"]
edizioni = [1, 2, 3, 2, 2, 1, 3, 3]
lunghezza = len(studenti)
for indice in range(lunghezza):  
    studente = studenti[indice]
    edizione = edizioni[indice]
    if edizione == 1:
        print(studente)



Alex
Faith


In [ ]:
#Esercizio 9
#Abbiamo una lista di stringhe di prezzi in dollari, che erroneamente sono stati scritti con il simbolo dell'euro: 
#prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"] 
#cambiare il simbolo dell'euro (€) in quello del dollaro ($) per ogni stringa nella lista; il risultato sarà memorizzato in un'altra lista.

In [116]:
prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"]

prezzi_dollaro = []
for prezzo in prezzi:
    prezzo_dollaro = prezzo.replace("€", "$")
    prezzi_dollaro.append(prezzo_dollaro)

print(prezzi_dollaro)


['100 $', '200 $', '500 $', '10 $', '50 $', '70 $']


In [ ]:
#Esercizio 10
#Abbiamo una lista di studenti: 
#studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"] 
#vogliamo dividere gli studenti in due squadre per un campionato di Uno nel seguente modo: 
#selezioneremo i nomi in posizione pari per un squadra, e i nomi in posizione dispari per l'altra. 
#Creiamo due liste per ogni squadra, e alla fine visualizziamole.

In [122]:
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"] 

studenti_pari = []
studenti_dispari = []
for i in range(len(studenti)):
    if i % 2 == 0:
        studente_pari = studenti[i]
        studenti_pari.append(studente_pari)
    else:
        studente_dispari = studenti[i]
        studenti_dispari.append(studente_dispari)
print("Gli studenti pari sono:", studenti_pari)
print("Gli studenti dispari sono:", studenti_dispari)
        

Gli studenti pari sono: ['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']
Gli studenti dispari sono: ['Bob', 'Dan', 'Faith', 'Henry', 'John']


In [180]:
#Soluzione alternativa
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"] 
studenti[0::2]

['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']

In [172]:
studenti[1::2]

['Bob', 'Dan', 'Faith', 'Henry', 'John']

In [ ]:
#Esercizio 11
#Abbiamo una lista con i guadagni degli ultimi 12 mesi (supponiamo da Gennaio a Dicembre): 
#guadagni = [100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50] 
#dobbiamo confrontare, stampando tutto a video, il guadagno di ogni mese con la media dei guadagni precedenti, e specificare nell'output se il guadagno attuale è maggiore o minore della media dei precedenti.

In [196]:
guadagni = [100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50]
conteggio = 1
somma = 0
for guadagno in guadagni:
    if conteggio == 1:
        print(f"Mese {conteggio}: {guadagno}")
    else:
        if guadagno < media:
            print(f"Mese {conteggio}: {guadagno} (media precedente: {media} - minore)")
        else:
            print(f"Mese {conteggio}: {guadagno} (media precedente: {media} - maggiore)")
    somma += guadagno
    media = somma / conteggio
    conteggio += 1

Mese 1: 100
Mese 2: 90 (media precedente: 100.0 - minore)
Mese 3: 70 (media precedente: 95.0 - minore)
Mese 4: 40 (media precedente: 86.66666666666667 - minore)
Mese 5: 50 (media precedente: 75.0 - minore)
Mese 6: 80 (media precedente: 70.0 - maggiore)
Mese 7: 90 (media precedente: 71.66666666666667 - maggiore)
Mese 8: 120 (media precedente: 74.28571428571429 - maggiore)
Mese 9: 80 (media precedente: 80.0 - maggiore)
Mese 10: 20 (media precedente: 80.0 - minore)
Mese 11: 50 (media precedente: 74.0 - minore)
Mese 12: 50 (media precedente: 71.81818181818181 - minore)
